GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
content-Type: application/json

{
    "name": "gay",
    "number": "123-1234567"
}

###
DELETE http://localhost:3001/api/persons/678f6ca8d846723c112db73b

###
GET http://localhost:3001/api/persons
###
PUT http://localhost:3001/api/persons/6790004d5ac8aa52e4349e1a HTTP/1.1
content-Type: application/json

{
    "name": "gay",
    "number": "111-1111111"
}
###
PUT http://localhost:3001/api/persons/6790004d5ac8aa52e4349e1a HTTP/1.1
content-Type: application/json

{
    "name": "gay",
    "number": "112-41asda"
}